version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: stock_management_db
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p1234" ]
      timeout: 20s
      retries: 10
